### ISSUE TITLE
Create React components for old views

### ISSUE THREAD

**Issue by iRobsc** [iRobsc/Dinner-planner#1]
We need React components for:

- [x] DinnerButton
- [x] DinnerButtonLink
- [x] Welcome
- [x] Sidebar
- [x] SidebarItem
- [x] Searchbar
- ~~[ ] FoodGrid~~ probably not needed
- [x] FoodItem
- [x] DishDetails
- [x] IngredientList
- [x] DinnerOverview (MyDinner)
- [x] RecipeList
- [x] RecipeItem

These are the ones I could think of now.

**Comment by willwull** [comment]
Completed in #51
